# Configurações de Conexão com o Oracle FIAP
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL

# Swagger e OpenAPI
quarkus.swagger-ui.path=/swagger
quarkus.smallrye-openapi.info-title=Simple Manager - Turma do Bem
quarkus.smallrye-openapi.info-version=1.0.0

# CORS Global e Flexível
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET, PUT, POST, DELETE, OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with, role

# Configurações do Mailer (Substitua pelos dados reais)
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=kaliel.aquino1303@gmail.com
quarkus.mailer.password=ztej jltx tkav qhna
quarkus.mailer.auth-methods=PLAIN
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.from=kaliel.aquino1303@gmail.com

